
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zemofhppkgtrxkbdrsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbW9maHBwa2d0cnhrYmRyc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTU1NDIsImV4cCI6MjA2MDEzMTU0Mn0.spu4KljZwMf-u7z60_DmSTXORk7hh_292YNYNNFbqL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to set up an admin user
export const setupAdminUser = async (userId: string, collegeId: string, title?: string) => {
  try {
    // Add admin role
    const { error: roleError } = await supabase
      .from('user_roles')
      .upsert({
        user_id: userId,
        role: 'admin'
      }, { onConflict: 'user_id,role' });

    if (roleError) throw roleError;

    // Add college admin
    const { error: adminError } = await supabase
      .from('college_admins')
      .upsert({
        user_id: userId,
        college_id: collegeId,
        title: title || 'Administrator'
      }, { onConflict: 'user_id,college_id' });

    if (adminError) throw adminError;

    return { success: true };
  } catch (error) {
    console.error('Error setting up admin user:', error);
    return { success: false, error };
  }
};

// Function to invite a user to join as a college admin
export const inviteCollegeAdmin = async (email: string, collegeId: string, title: string) => {
  try {
    // This would typically involve sending an email invitation
    // For now, we'll just create the admin record if the user exists
    
    // First, check if the user exists by email
    const { data: profiles, error: profileError } = await supabase
      .from('profiles')
      .select('id')
      .eq('email', email)
      .limit(1);
    
    if (profileError) throw profileError;
    
    if (profiles && profiles.length > 0) {
      const userId = profiles[0].id;
      
      // Set up the admin user
      return await setupAdminUser(userId, collegeId, title);
    } else {
      return { 
        success: false, 
        error: { message: 'User with this email does not exist' } 
      };
    }
  } catch (error) {
    console.error('Error inviting college admin:', error);
    return { success: false, error };
  }
};
