// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zemofhppkgtrxkbdrsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbW9maHBwa2d0cnhrYmRyc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTU1NDIsImV4cCI6MjA2MDEzMTU0Mn0.spu4KljZwMf-u7z60_DmSTXORk7hh_292YNYNNFbqL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);